import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ghahve Khaneh",
  description: "Generated by Parham Kohanbaba",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="nav">
          <Link href={'/'}>خانه</Link>
          <Link href={'/pages/History'}>تاریخچه قهوه</Link>
          <Link href={'/pages/Types'}>انواع دانه قهوه</Link>
          <Link href={'/pages/Benefits'}>فواید قهوه</Link>
          <Link href={'/pages/CoffeeTypes'}> انواع سرو  </Link>
          <Link href={'./'}>محصولات ما</Link>
          <Link href={'./'}>درباره ما</Link>
          <Link href={'./'}>تماس با ما</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
